'use client';
import { LuxuryItem, PipelineLog } from "../types";

export const INITIAL_LUXURY_ITEMS: LuxuryItem[] = [
  {
    id: "lux-001",
    title: "Submariner Date 126610LN",
    category: "Watches",
    brand: "Rolex",
    price: 14500,
    currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80",
    affiliateUrl: "https://www.chrono24.com/rolex/submariner-date--id12345.htm",
    merchantName: "Chrono24",
    network: "Rakuten",
    inStock: true,
    score: 98,
    metrics: {
      ctr: 4.2,
      conversionRate: 1.8,
      epc: 12.5,
    },
  },
  {
    id: "lux-002",
    title: "Birkin 30 Gold Togo Leather",
    category: "Bags",
    brand: "Hermès",
    price: 28900,
    currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=80",
    affiliateUrl: "https://www.farfetch.com/shopping/women/hermes-pre-owned-birkin-30-bag-item-1234.aspx",
    merchantName: "Farfetch",
    network: "CJ",
    inStock: true,
    score: 95,
    metrics: {
      ctr: 5.1,
      conversionRate: 2.3,
      epc: 18.2,
    },
  },
  {
    id: "lux-003",
    title: "Royal Oak Selfwinding 15500ST",
    category: "Watches",
    brand: "Audemars Piguet",
    price: 42000,
    currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1547996160-01c1782698e0?auto=format&fit=crop&w=800&q=80",
    affiliateUrl: "https://www.jomashop.com/audemars-piguet-watch-15500st.html",
    merchantName: "Jomashop",
    network: "Direct",
    inStock: false,
    score: 92,
    metrics: {
      ctr: 3.8,
      conversionRate: 1.2,
      epc: 9.4,
    },
  },
  {
    id: "lux-004",
    title: "Limited Edition Lithograph (1974)",
    category: "Art",
    brand: "Alexander Calder",
    price: 18500,
    currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=800&q=80",
    affiliateUrl: "https://www.sothebys.com/en/buy/auction/2026/prints/calder-litho",
    merchantName: "Sotheby's",
    network: "Impact",
    inStock: true,
    score: 96,
    metrics: {
      ctr: 2.9,
      conversionRate: 1.5,
      epc: 14.1,
    },
  },
];

export const INITIAL_LOGS: PipelineLog[] = [
  {
    id: "log-1",
    timestamp: "2026-08-31T10:00:12Z",
    phase: 1,
    agent: "Chrono24 Collector",
    message: "Verified price delta across 4 luxury watch references.",
    status: "success",
  },
  {
    id: "log-2",
    timestamp: "2026-08-31T09:58:04Z",
    phase: 2,
    agent: "Trust Guard",
    message: "Validated serial tracking hashes against counterfeit databases.",
    status: "info",
  },
];